# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Laal227yN8udY8n2lQR3Q8PN3y0jTHT
"""



#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input().strip())

if N%2!=0:
    print('Weird')
elif N%2==0 and N>=2 and N<=5:
    print('Not Weird')
elif N%2==0 and N>=6 and N<=20:
    print('Weird')
else:
    print('Not Weird')