# -*- coding: utf-8 -*-
"""HackerRank_30_days_of_Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ko2VUEzyQKWnH2p_3T78k1O3eqjmnbi
"""



i = 4
d = 4.0
s = 'HackerRank '
# Declare second integer, double, and String variables.
input_int = int(input())
input_flt = float(input())
input_str = str(input())

# Read and save an integer, double, and String to your variables.
a1 = (i + input_int)
b1 = (d + input_flt)
c1 = (s + input_str)
# Print the sum of both integer variables on a new line.
print(a1)
# Print the sum of the double variables on a new line.
print(b1)
# Concatenate and print the String variables on a new line
print(c1)
# The 's' variable above should be printed first.



