# -*- coding: utf-8 -*-
"""hackerrank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Laal227yN8udY8n2lQR3Q8PN3y0jTHT
"""

#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    n = int(input().strip())


for i in range(1, 11):
  a = n * i
  print(n, 'x', i, '=', a)

