# -*- coding: utf-8 -*-
"""hackerrank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Laal227yN8udY8n2lQR3Q8PN3y0jTHT
"""

input1 = int(input())

for i in range(input1):
  str1 = list(input())
  for a in range(len(str1)):
    if a%2 == 0:
      print(str1[a], end = "")
  print(' ', end = "")
    
  for a in range(len(str1)):
     if a%2!= 0:
      print(str1[a], end = "")
  print(' ', end = "")
  print()

