# -*- coding: utf-8 -*-
"""hackerrank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Laal227yN8udY8n2lQR3Q8PN3y0jTHT
"""



#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

for i in arr:
  a = arr[::-1]

string = ''
for i in range(len(a)):
  string = string + str(a[i]) + ' '
print(string)